### get hub config
GET {{hue_bridge_url}}/api/config HTTP/1.1

### check authentication
GET {{hue_bridge_url}}/auth/v1 HTTP/1.1
hue-application-key: {{hue_api_key}}

### get account
GET {{hue_bridge_url}}/api/{{hue_api_key}}/config HTTP/1.1

### generate api key
### press link button on Hub, then send request
POST {{hue_bridge_url}}/api HTTP/1.1
Content-Type: application/json

{"devicetype":"app_name#instance_name", "generateclientkey":true}

> {%
    // Extract the API key from the response
    // To use it in the future, manually save it in `hue_api_key` of your ###.env.json file
    const body = Array.isArray(response.body) ? response.body[0] : response.body;

    client.test("Check for success object", function() {
        client.assert(body && body.success, "Response did not contain a 'success' object. Check if the link button was pressed.");
    });

    if (body && body.success && body.success.username) {
        client.global.set("hue_api_key", body.success.username);
        client.log("Successfully captured API Key: " + client.global.get("hue_api_key"));
    }
%}

### get resources
GET {{hue_bridge_url}}/clip/v2/resource HTTP/1.1
hue-application-key: {{hue_api_key}}

### get scenes
### Scenes are used to store and recall settings for a group of lights.
GET {{hue_bridge_url}}/clip/v2/resource/scene HTTP/1.1
hue-application-key: {{hue_api_key}}

### get rooms
### Rooms group devices and each device can only be part of one room.
GET {{hue_bridge_url}}/clip/v2/resource/room HTTP/1.1
hue-application-key: {{hue_api_key}}

### get zones
### Zones group services and each service can be part of multiple zones.
GET {{hue_bridge_url}}/clip/v2/resource/zone HTTP/1.1
hue-application-key: {{hue_api_key}}

### get grouped lights
GET {{hue_bridge_url}}/clip/v2/resource/grouped_light HTTP/1.1
hue-application-key: {{hue_api_key}}

### get light services
### These are offered by devices with lighting capabilities.
GET {{hue_bridge_url}}/clip/v2/resource/light HTTP/1.1
hue-application-key: {{hue_api_key}}

> {%
    // Extract the first light ID for the next requests
    // To use it in the future, manually save it in `hue_light_id` of your ###.env.json file
    client.test("Extract first light", function() {
        const body = response.body;

        client.assert(body && Array.isArray(body.data) && body.data.length > 0, "No data found in response");

        const firstLight = body.data.find(item => item.type === "light");
        client.assert(firstLight, "No resource with type 'light' found in the data array");

        client.global.set("hue_light_id", firstLight.id);
        client.log("Selected Light ID: " + client.global.get("hue_light_id"));
    });
%}

### get a specific hub light
GET {{hue_bridge_url}}/clip/v2/resource/light/{{hue_light_id}} HTTP/1.1
hue-application-key: {{hue_api_key}}

### turn light on
PUT {{hue_bridge_url}}/clip/v2/resource/light/{{hue_light_id}} HTTP/1.1
hue-application-key: {{hue_api_key}}

{
  "on": {
    "on": true
  }
}

### turn light off
PUT {{hue_bridge_url}}/clip/v2/resource/light/{{hue_light_id}} HTTP/1.1
hue-application-key: {{hue_api_key}}

{
  "on": {
    "on": false
  }
}

### get temperature services
GET {{hue_bridge_url}}/clip/v2/resource/temperature HTTP/1.1
hue-application-key: {{hue_api_key}}

### get light level services
GET {{hue_bridge_url}}/clip/v2/resource/light_level HTTP/1.1
hue-application-key: {{hue_api_key}}
